name: Publish to Maven Repository
on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    branches: [main]
    types:
      - completed
jobs:
  publish-maven:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # only if CI passed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Publish to maven repository
        run: ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.SPACE_MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SPACE_MAVEN_PASSWORD }}
